/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Factory } from "./ERC20Factory";
export type { ERC721Factory } from "./ERC721Factory";
export type { MRC20 } from "./MRC20";
export type { WrapMRC721UpgradeableTest } from "./WrapMRC721UpgradeableTest";
