/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReverseRegistrar__factory } from "./IReverseRegistrar__factory";
export { ReverseClaimer__factory } from "./ReverseClaimer__factory";
