/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMRC20 } from "./IMRC20";
export type { IMRC721 } from "./IMRC721";
export type { IMarketService } from "./IMarketService";
export type { IMarketServicePackage } from "./IMarketServicePackage";
export type { IMarketServiceUser } from "./IMarketServiceUser";
