/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dnssecOracle from "./dnssec-oracle";
export type { dnssecOracle };
import type * as ethregistrar from "./ethregistrar";
export type { ethregistrar };
import type * as registry from "./registry";
export type { registry };
import type * as resolvers from "./resolvers";
export type { resolvers };
import type * as reverseRegistrar from "./reverseRegistrar";
export type { reverseRegistrar };
import type * as wrapper from "./wrapper";
export type { wrapper };
